---
#
# Ansible managed
#
repository:
  description: Installs python pip and packages with pip
  homepage: https://mullholland.net
  topics: development, packaging, system, ansible, molecule, playbook
