---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    pip_packages:
      - "python-dateutil"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_version }}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"

    - name: Check pip3 is executable
      ansible.builtin.command:
        cmd: pip3 --version
      changed_when: false
      register: pip3_version

    - name: Assert pip3 is functional
      ansible.builtin.assert:
        that:
          - pip3_version.rc == 0
        fail_msg: "pip3 --version failed: {{ pip3_version.stderr }}"
